import React, { useEffect } from 'react';

const Home = ({ onPageChange }) => {
  useEffect(() => {
    const heatmapGrid = document.querySelector(".heatmap-grid");
    if(heatmapGrid) {
      // Clear existing cells before generating new ones
      heatmapGrid.innerHTML = '';
      for (let i = 0; i < 24; i++) {
          const cell = document.createElement("div");
          cell.classList.add("heatmap-cell");
          let cellType = 'low';
          if (i % 7 === 0) cellType = 'severe';
          else if (i % 5 === 0) cellType = 'high';
          cell.classList.add(cellType);
          heatmapGrid.appendChild(cell);
      }
    }
  }, []);

  return (
    <section id="home" className="page active">
      {/* Hero Section */}
      <section className="hero">
        <div className="container hero-content">
          <div className="hero-text">
            <div className="badge">
              <svg className="shield-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
                <path d="m9 12 2 2 4-4"/>
              </svg>
              Government-backed Initiative
            </div>
            <h1 className="hero-title">
              Smart Tourism, Safe Tourism
            </h1>
            <p className="hero-description">
              Smart Tourist Safety Monitoring & Incident Response System.
              Trusted, modern and accessible for every citizen.
            </p>
            <div className="hero-buttons">
              <a href="#register" className="btn btn-primary btn-lg" onClick={() => onPageChange('register')}>Register as Tourist</a>
              <a href="#help" className="btn btn-outline btn-lg" onClick={() => onPageChange('help')}>Help & Support</a>
            </div>
            <div className="hero-features">
              <div className="feature">
                <svg className="feature-icon secure" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
                  <path d="m9 12 2 2 4-4"/>
                </svg>
                Secure
              </div>
              <div className="feature">
                <svg className="feature-icon zones" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <polygon points="3 11 22 2 13 21 11 13 3 11"/>
                </svg>
                Live Zones
              </div>
              <div className="feature">
                <svg className="feature-icon support" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/>
                </svg>
                24x7 Support
              </div>
            </div>
          </div>
          <div className="hero-visual">
            <div className="risk-map-demo">
              <div className="map-header">
                <h3>Risk Map (Demo)</h3>
                <span className="map-legend">High-risk in red</span>
              </div>
              <div className="heatmap-grid">
                {/* Grid items will be generated by useEffect */}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="features">
        <div className="container">
          <div className="features-grid">
            <div className="feature-card">
              <div className="feature-card-header">
                <svg className="feature-card-icon" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/>
                  <circle cx="9" cy="7" r="4"/>
                  <path d="m22 21-3-3m0 0L16 15m3 3 3-3m-3 3v-6"/>
                </svg>
                <h3>Digital Tourist ID</h3>
              </div>
              <p className="feature-card-description">
                QR-enabled ID for quick verification at checkpoints and services.
              </p>
            </div>

            <div className="feature-card">
              <div className="feature-card-header">
                <svg className="feature-card-icon orange" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/>
                  <line x1="12" y1="9" x2="12" y2="13"/>
                  <line x1="12" y1="17" x2="12.01" y2="17"/>
                </svg>
                <h3>Safety Alerts</h3>
              </div>
              <p className="feature-card-description">
                Receive real-time advisories and area warnings based on your route.
              </p>
            </div>

            <div className="feature-card">
              <div className="feature-card-header">
                <svg className="feature-card-icon green" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/>
                </svg>
                <h3>Emergency Help</h3>
              </div>
              <p className="feature-card-description">
                One-tap call and WhatsApp to reach police, ambulance, and helplines.
              </p>
            </div>

            <div className="feature-card">
              <div className="feature-card-header">
                <svg className="feature-card-icon" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <circle cx="12" cy="12" r="10"/>
                  <path d="M12 16v-4"/>
                  <path d="M12 8h.01"/>
                </svg>
                <h3>About the Project</h3>
              </div>
              <p className="feature-card-description">
                Transparent, privacy-first, aligned with public safety objectives.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Why It Matters Section */}
      <section className="why-matters">
        <div className="container">
          <div className="why-matters-grid">
            <div className="why-matters-content">
              <h2>Why it matters</h2>
              <p>
                Designed for all citizens including elderly and rural users.
                Simple language, clear icons, and accessible controls.
              </p>
            </div>
            <div className="active-alerts-card">
              <div className="active-alerts-title">Active Alerts</div>
              <ul className="alerts-list">
                <li className="alert-item">
                  <span className="alert-info">
                    <span className="alert-dot severe"></span>
                    Heavy crowd near Fort
                  </span>
                  <span className="alert-level severe">Severe</span>
                </li>
                <li className="alert-item">
                  <span className="alert-info">
                    <span className="alert-dot high"></span>
                    Road closure at Market
                  </span>
                  <span className="alert-level high">High</span>
                </li>
                <li className="alert-item">
                  <span className="alert-info">
                    <span className="alert-dot low"></span>
                    Weather advisory
                  </span>
                  <span className="alert-level low">Low</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
    </section>
  );
};

export default Home;